config/routes.rb
Serveforcommunity::Application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users do
  resources :services
  end

  resources :users
  resources :services do
    collection do
      get 'search'
      post 'quickadd'
    end
  end

  get '/user/services', to: 'services#my_index'
  post '/user/addservice', to: 'users#add_service'

  root to: 'welcome#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

end

app/models/location.rb
class Location < ActiveRecord::Base

  belongs_to :service
  has_many :user, through: :service

end

app/models/service.rb
class Service < ActiveRecord::Base
    has_and_belongs_to_many :users

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :information, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  validates(:name, presence: true)
  validates(:email, uniqueness: true,
                    presence: true)
  validates(:password, presence: true,
                       length: { minimum: 5,
                                 message: 'must be at least 5 characters'})
  has_secure_password
  has_and_belongs_to_many :services
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin
    current_user.admin if current_user
  end

  def require_authentication
    flash[:auth_error] = 'You must be logged in to view that page'
    redirect_to login_path unless current_user
  end

  def require_admin_authentication
    redirect_to root_path unless current_admin
  end


end

app/controllers/favorites_controller.rb
# class PlaylistsController < ApplicationController
#   def index
#     @user = User.find(params[:user_id])
#     @playlists = @user.playlists
#   end

#   def show
#     @playlist = Playlist.find(params[:id])
#     @songs = @playlist.songs
#   end

# end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :require_authentication, only: [:index, :show, :update, :destroy]

  def index
    @services = Service.all.order(created_at: :desc)
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.id = current_user
    if @service.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def service_params
    return params.require(:service).permit(:name, :address, :information)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:login_error] = 'Invalid email and/or password'
      render 'new'
    end
  end

  def destroy
    flash[:auth_error] = nil
    session[:user_id] = nil
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_authentication, only: [:index, :show, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    # Only admins can create users while logged in
    require_admin_authentication if current_user
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    return params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serve For Community</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<link href="//netdna.bootstrapcdn.com/bootswatch/3.1.1/readable/bootstrap.min.css" rel="stylesheet">
  <style>li{margin-bottom:0;}</style>
</head>
<body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <ul class="nav navbar-nav > li > a {padding-top:10px !important; padding-bottom:10px !important;}
            navbar {min-height:40px !important}">
            <li><img src="http://www.logomaker.com/logo-images/a100e43d36036479.gif" width="125" height="55"/>
            </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user  %>
              <li>Hello, <%= current_user.name %>!</li>
              <li><%= link_to "My Services", "/users/#{current_user.id}" %> </li>
               <li><%= link_to "New Services", "/services/new" %> </li>
              <li><%= link_to_unless_current 'Logout', logout_path %> </li>
            <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to "Sign up", new_user_path %></li>
            <% end %>
    </div>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/services/_form.html.erb
<%= form_for @service do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :information %><br>
    <%= f.text_field :information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Services</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %>
<%= link_to 'Back', users_path %>

app/views/services/index.html.erb
<p>Services</p>
<% @services.each do |service| %>
  <p><a href="<%= service.name %>"><%= service.address %></a> Posted by: <%= link_to "#{service.user.name}", user_path(service.user) %></p> <br>
<% end %>


<br>
<br>
<br>
<br>
<br>
<br>
<th><font size="4"><b>Education</b></font></th>
<br>
<br>
<iframe width="500" height="300" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col1+from+1H9_3LGoOZ90io4ncxoIYugia_YrBuwv_croMeH-S&amp;viz=MAP&amp;h=false&amp;lat=40.72002690182591&amp;lng=-73.96325030146488&amp;t=1&amp;z=11&amp;l=col1&amp;y=2&amp;tmplt=2&amp;hml=GEOCODABLE"></iframe>
<br>
<br>
<br>
<br>
<br>
<br>
 <th><font size="4"><b>Health</b></font><b></th>
<br>
<br>
<iframe width="500" height="300" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col6+from+1_O5NumVaw1b6ndQ9yhw20xZp5Vqzi9ZgrBtsNhnd&amp;viz=MAP&amp;h=false&amp;lat=40.742759466553174&amp;lng=-73.91896780039065&amp;t=1&amp;z=11&amp;l=col6&amp;y=2&amp;tmplt=2&amp;hml=GEOCODABLE"></iframe><br><br><br><br>
<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>Create a New Service</h1><br>
<%= form_for([@user, @service]) do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

   <div>
    <%= f.label :information %>
    <%= f.text_field :information %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/services/show.html.erb
<h3><%= @service.name %></h3>
<p><strong>Name: </strong><%= @service.name %></p>
<p><strong>Address: </strong><%= @service.address %></p>
<p><strong>Information: </strong><%= @service.information %></p>
<p>
  <%= link_to "All", services_path %>
  <%= link_to "Edit", edit_service_path(@service) %>
  <%= link_to 'Destroy', @service, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Home', root_path %>
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address, required: true %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

    <div>
    <%= f.label :information %>
    <%= f.text_field :information %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password, required: true %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, required: true %>
  </div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Information</th>
      <th>Email</th>
      <th>Created_at</th>
      <th>Updated_at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
         <td><%= user.information %></td>
         <td><%= user.email %></td>
        <td><%= user.created_at %></td>
         <td><%= user.updated_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>Hello <%= @user.name %></p>

<div class="services">
  <% @user.services.order(created_at: :desc).each do |service| %>
    <a href= "<%= service.name %>"><%= service.address %></a> <br> <br>
  <% end %>
</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>address:</strong>
  <%= @user.address %>
</p>


<p>
  <strong>information:</strong>
  <%= @user.information %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', user_path %>
<%= link_to 'Home', root_path %>

app/views/welcome/index.html.erb
<p class= "col-md-7">

<b><font size="12"><font color="midnightblue">Serve For Community</font></font></b>
  <br>
  <br>
  <br>
<b><font size="4"><u>What We Do</u></font></b>
  <br>
  <br>


  <br>
<b>Problem:</b>
  <br>
  <br>
There are so many people in the world who don't have access to affordable healthcare, quality education, or culture/art. Although there are a plethora of community programs available, oftentimes the people who need it the most, fall through the cracks.
  <br>
  <br>
<b>Solution:</b>
  <br>
  <br>
Instead of searching through long lists and individual websites, SERVETHECOMMUNITY provides a comprehensive place for people who are seeking community assistance. It also provides opportunities for people who are looking to help their community directly.
  <br>
Not only can people see what services are available, but they can then research causes that they want to be involved in. This will help with community outreach from both sides.
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>


<div><iframe width="500" height="300" scrolling="no" frameborder="no" src="https://www.google.com/fusiontables/embedviz?q=select+col0+from+1yRBEgAORqSyf12sCiGuJ100O9eBBviE7ATtp2Cv3&amp;viz=MAP&amp;h=false&amp;lat=28.7489199219673&amp;lng=-98.35353125&amp;t=1&amp;z=3&amp;l=col0&amp;y=4&amp;tmplt=4&amp;hml=ONE_COL_LAT_LNG"></iframe></div>
    <br>
    <br>
    <br>
    <br>
<footer>

      <p align="right">
  <img src="http://www.nyc.gov/html/doitt/images/features/init_opendata.png" alt="Community Service" width="100" height="71">
  <img src="http://www.midlothian-isd.net/mhs/_img/community-service.jpg" alt="Community Service" width="100" height="71">
    <br>
    <br>
    <br>
    <br>
      <p align="right"><b>Created by: Nathan Plutzik<b></p>
      <p align="right"><b>Contact information:<b> <a href="mailto:nate@nateplutzik.com"><b>nate@nateplutzik.com<b></a></p>
</footer>
</body>
</html>